### ISSUE TITLE
License conditions

### ISSUE THREAD

**Issue by networkfusion** [PervasiveDigital/jsonnetmf#1]
Hi, one of the contributors to nanoframework has ported this lib to work with it. However the source files all state that a written license is required, although the license in the root of the repo is Apache 2... which one takes precedence here? If it is the latter, the nf project would be unable to accept the change and perhaps you would accept the PR here. If the former, is it possible to remove the incorrect license from the source files?

**Comment by martincalsyn** [comment]
Thanks for the contribution!
